#pragma once
#include <string>
#include <vector>
#include "audioplugins/common/analysis/PresetData.h"

// Loads presets from the compile-time embedded built-in set (generated by
// CMakeLists.txt's EmbeddedPresets step) and from a user directory.
// Discovery order:
//   1. Built-in presets, embedded at configure time (always present)
//   2. User presets from getUserPresetsDir() -- loaded on top, override by name
// The final list is sorted alphabetically by name.
class PresetManager
{
public:
    PresetManager();

    int getNumPresets() const noexcept { return static_cast<int> (presets_.size()); }
    const audioplugins::common::analysis::PresetData& getPreset (int i) const noexcept { return presets_[static_cast<size_t> (i)]; }

    // Returns the directory where user presets are stored (created on first access if absent).
    std::string getUserPresetsDir() const;

    // Re-scans the user directory and merges with the built-in presets.
    void refresh();

    // Returns the index of the preset with the given name, or -1 if not found.
    int findByName (const std::string& name) const;

private:
    void loadBuiltIn();
    void mergeFromDirectory (const std::string& dir);

    std::vector<audioplugins::common::analysis::PresetData> presets_;
};
